### ISSUE TITLE
[Code] Error running `dgp`

### ISSUE THREAD

**Issue by JJ** [JJ/2021-cec-deep-g-prop#11]
I get this error after following instructions in the README and trying to run it

```
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True
...
relocation R_X86_64_PC32 against symbol `PyFloat_Type' can not be used when making a shared object; recompile con -fPIC.
```

No idea what it means.

**Comment by JJ** [comment]
[This](https://github.com/rapidsai/cudf/issues/4375) might be the key. Apparently it works only up to version 3.7.

**Comment by JJ** [comment]
No, no cigar. does not work with 3.7.9 either:

```
Exception: Compilation failed (return status=1): /usr/bin/ld: /home/jmerelo/.pyenv/versions/3.7.9/lib/libpython3.7m.a(abstract.o): relocation R_X86_64_PC32 against symbol `_Py_NotImplementedStruct' can not be used when making a shared object; recompile con -fPIC. /usr/bin/ld: falló el enlace final: bad value. collect2: error: ld returned 1 exit status. 
```

**Comment by JJ** [comment]
Pyenv does not seem to work well with this [due to this](https://stackoverflow.com/questions/21342931/error-importing-theano)

**Comment by JJ** [comment]
OK [solution here](https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with---enable-shared)
